version: "3"
services:
    airport-backend:
        build: ./Server
        container_name: airport-back
        ports:
            - 8080:8080

    airport-frontend:
        build: ./WebClient
        container_name: airport-ui
        ports:
            - 8976:8976
        links:
            - airport-back
    nginx-api:
        build: ./Nginx
        container_name: api
        ports:
            - 80:80
        depeneds_on:
            - "airport-back"
            - "airport-ui"
